# generated by datamodel-codegen:
#   filename:  openapi3.json
#   timestamp: 2026-04-05T12:51:54+00:00

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, BaseModel, Field


class SourcePackage(BaseModel):
    name: str | None = Field(
        None, description='Name of the project', examples=['Copr repository']
    )
    url: AnyUrl | None = None
    version: str | None = Field(None, examples=['1.0'])


class PaginationMeta(BaseModel):
    limit: int | None = Field(None, description='Limit', examples=[20])
    offset: int | None = Field(None, description='Offset', examples=[0])
    order: str | None = Field(None, description='Order by', examples=['id'])
    order_type: str | None = Field(None, description='Order type', examples=['DESC'])


class SourceChroot(BaseModel):
    state: str | None = Field(None, description='', examples=['succeeded'])
    result_url: AnyUrl | None = None


class SourceBuildConfig(BaseModel):
    source_type: str | None = Field(
        None,
        description='See https://python-copr.readthedocs.io/en/latest/client_v3/package_source_types.html',
        examples=['scm'],
    )
    source_dict: dict[str, Any] | None = Field(
        None,
        description='http://python-copr.readthedocs.io/en/latest/client_v3/package_source_types.html',
    )
    memory_limit: int | None = None
    timeout: int | None = Field(
        18000,
        description='Number of seconds we allow the builds to run.',
        examples=[123123],
    )
    is_background: bool | None = Field(
        None, description='The build is marked as a background job'
    )


class CreateBuildUrl(BaseModel):
    chroot_names: list[str] | None = Field(
        None,
        description='List of chroot names',
        examples=[['fedora-37-x86_64', 'fedora-rawhide-x86_64']],
    )
    background: bool | None = Field(
        None, description='The build is marked as a background job'
    )
    timeout: int | None = Field(
        18000,
        description='Number of seconds we allow the builds to run.',
        examples=[123123],
    )
    bootstrap: str | None = Field(
        None,
        description="Mock bootstrap feature setup. Possible values are 'default', 'on', 'off', 'image'.",
    )
    isolation: str | None = Field(
        None,
        description="Mock isolation feature setup. Possible values are 'default', 'simple', 'nspawn'.",
        examples=['nspawn'],
    )
    after_build_id: int | None = Field(
        None,
        description='Build after the batch containing the Build ID build',
        examples=[123],
    )
    with_build_id: int | None = Field(
        None,
        description='Build in the same batch with the Build ID build',
        examples=[123],
    )
    enable_net: bool | None = Field(
        None, description='Enable internet access during builds'
    )
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    projectname: str | None = Field(
        None, description='Name of the project', examples=['copr-dev']
    )
    project_dirname: str | None = Field(
        None, description='', examples=['copr-dev:pr:123']
    )
    pkgs: list[AnyUrl] | None = Field(
        None,
        description='List of urls to build from',
        examples=[['https://example.com/some.src.rpm']],
    )


class CreateBuildUpload(BaseModel):
    chroot_names: list[str] | None = Field(
        None,
        description='List of chroot names',
        examples=[['fedora-37-x86_64', 'fedora-rawhide-x86_64']],
    )
    background: bool | None = Field(
        None, description='The build is marked as a background job'
    )
    timeout: int | None = Field(
        18000,
        description='Number of seconds we allow the builds to run.',
        examples=[123123],
    )
    bootstrap: str | None = Field(
        None,
        description="Mock bootstrap feature setup. Possible values are 'default', 'on', 'off', 'image'.",
    )
    isolation: str | None = Field(
        None,
        description="Mock isolation feature setup. Possible values are 'default', 'simple', 'nspawn'.",
        examples=['nspawn'],
    )
    after_build_id: int | None = Field(
        None,
        description='Build after the batch containing the Build ID build',
        examples=[123],
    )
    with_build_id: int | None = Field(
        None,
        description='Build in the same batch with the Build ID build',
        examples=[123],
    )
    enable_net: bool | None = Field(
        None, description='Enable internet access during builds'
    )
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    projectname: str | None = Field(
        None, description='Name of the project', examples=['copr-dev']
    )
    project_dirname: str | None = Field(
        None, description='', examples=['copr-dev:pr:123']
    )
    pkgs: list[dict[str, Any]] | None = Field(
        None, description='application/x-rpm files to build from'
    )


class CreateBuildSCM(BaseModel):
    clone_url: AnyUrl | None = Field(
        None,
        description='URL to your Git or SVN repository',
        examples=['https://github.com/fedora-copr/copr.git'],
    )
    committish: str | None = Field(
        None,
        description='Specific branch, tag, or commit that you want to build',
        examples=['main'],
    )
    spec: str | None = Field(
        None,
        description='Path to your .spec file under the specified subdirectory',
        examples=['copr-cli.spec'],
    )
    subdirectory: str | None = Field(
        None,
        description='Subdirectory where source files and .spec are located',
        examples=['cli'],
    )
    chroot_names: list[str] | None = Field(
        None,
        description='List of chroot names',
        examples=[['fedora-37-x86_64', 'fedora-rawhide-x86_64']],
    )
    background: bool | None = Field(
        None, description='The build is marked as a background job'
    )
    timeout: int | None = Field(
        18000,
        description='Number of seconds we allow the builds to run.',
        examples=[123123],
    )
    bootstrap: str | None = Field(
        None,
        description="Mock bootstrap feature setup. Possible values are 'default', 'on', 'off', 'image'.",
    )
    isolation: str | None = Field(
        None,
        description="Mock isolation feature setup. Possible values are 'default', 'simple', 'nspawn'.",
        examples=['nspawn'],
    )
    after_build_id: int | None = Field(
        None,
        description='Build after the batch containing the Build ID build',
        examples=[123],
    )
    with_build_id: int | None = Field(
        None,
        description='Build in the same batch with the Build ID build',
        examples=[123],
    )
    enable_net: bool | None = Field(
        None, description='Enable internet access during builds'
    )
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    projectname: str | None = Field(
        None, description='Name of the project', examples=['copr-dev']
    )
    project_dirname: str | None = Field(
        None, description='', examples=['copr-dev:pr:123']
    )
    scm_type: str | None = Field("Possible values are 'git', 'svn'", examples=['git'])
    source_build_method: str | None = Field(
        None,
        description='https://docs.pagure.org/copr.copr/user_documentation.html#scm',
        examples=['tito'],
    )


class CreateBuildDistGit(BaseModel):
    chroot_names: list[str] | None = Field(
        None,
        description='List of chroot names',
        examples=[['fedora-37-x86_64', 'fedora-rawhide-x86_64']],
    )
    background: bool | None = Field(
        None, description='The build is marked as a background job'
    )
    timeout: int | None = Field(
        18000,
        description='Number of seconds we allow the builds to run.',
        examples=[123123],
    )
    bootstrap: str | None = Field(
        None,
        description="Mock bootstrap feature setup. Possible values are 'default', 'on', 'off', 'image'.",
    )
    isolation: str | None = Field(
        None,
        description="Mock isolation feature setup. Possible values are 'default', 'simple', 'nspawn'.",
        examples=['nspawn'],
    )
    after_build_id: int | None = Field(
        None,
        description='Build after the batch containing the Build ID build',
        examples=[123],
    )
    with_build_id: int | None = Field(
        None,
        description='Build in the same batch with the Build ID build',
        examples=[123],
    )
    enable_net: bool | None = Field(
        None, description='Enable internet access during builds'
    )
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    projectname: str | None = Field(
        None, description='Name of the project', examples=['copr-dev']
    )
    distgit: str | None = Field(
        None, description='Dist-git URL we build against', examples=['fedora']
    )
    namespace: str | None = Field(
        None, description='DistGit namescape', examples=['@copr/copr']
    )
    package_name: str | None = Field(
        None, description='Name of the package', examples=['copr-cli']
    )
    committish: str | None = Field(
        None,
        description='Specific branch, tag, or commit that you want to build',
        examples=['main'],
    )
    project_dirname: str | None = Field(
        None, description='', examples=['copr-dev:pr:123']
    )


class CreateBuildPyPI(BaseModel):
    pypi_package_name: str | None = Field(
        None, description='Package name in the Python Package Index.', examples=['copr']
    )
    pypi_package_version: str | None = Field(
        None, description='PyPI package version', examples=['1.128pre']
    )
    spec_generator: str | None = Field(
        None,
        description='Tool for generating specfile from a PyPI package. The options are full-featured pyp2rpm with cross distribution support, and pyp2spec that is being actively developed and considered to be the future.',
        examples=['pyp2spec'],
    )
    spec_template: str | None = Field(
        None,
        description='Name of the spec template. This option is limited to pyp2rpm spec generator.',
        examples=['default'],
    )
    python_versions: list[str] | None = Field(
        None,
        description='For what python versions to build. This option is limited to pyp2rpm spec generator.',
        examples=[['3', '2']],
    )
    chroot_names: list[str] | None = Field(
        None,
        description='List of chroot names',
        examples=[['fedora-37-x86_64', 'fedora-rawhide-x86_64']],
    )
    background: bool | None = Field(
        None, description='The build is marked as a background job'
    )
    timeout: int | None = Field(
        18000,
        description='Number of seconds we allow the builds to run.',
        examples=[123123],
    )
    bootstrap: str | None = Field(
        None,
        description="Mock bootstrap feature setup. Possible values are 'default', 'on', 'off', 'image'.",
    )
    isolation: str | None = Field(
        None,
        description="Mock isolation feature setup. Possible values are 'default', 'simple', 'nspawn'.",
        examples=['nspawn'],
    )
    after_build_id: int | None = Field(
        None,
        description='Build after the batch containing the Build ID build',
        examples=[123],
    )
    with_build_id: int | None = Field(
        None,
        description='Build in the same batch with the Build ID build',
        examples=[123],
    )
    enable_net: bool | None = Field(
        None, description='Enable internet access during builds'
    )
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    projectname: str | None = Field(
        None, description='Name of the project', examples=['copr-dev']
    )
    project_dirname: str | None = Field(
        None, description='', examples=['copr-dev:pr:123']
    )


class CreateBuildRubyGems(BaseModel):
    chroot_names: list[str] | None = Field(
        None,
        description='List of chroot names',
        examples=[['fedora-37-x86_64', 'fedora-rawhide-x86_64']],
    )
    background: bool | None = Field(
        None, description='The build is marked as a background job'
    )
    timeout: int | None = Field(
        18000,
        description='Number of seconds we allow the builds to run.',
        examples=[123123],
    )
    bootstrap: str | None = Field(
        None,
        description="Mock bootstrap feature setup. Possible values are 'default', 'on', 'off', 'image'.",
    )
    isolation: str | None = Field(
        None,
        description="Mock isolation feature setup. Possible values are 'default', 'simple', 'nspawn'.",
        examples=['nspawn'],
    )
    after_build_id: int | None = Field(
        None,
        description='Build after the batch containing the Build ID build',
        examples=[123],
    )
    with_build_id: int | None = Field(
        None,
        description='Build in the same batch with the Build ID build',
        examples=[123],
    )
    enable_net: bool | None = Field(
        None, description='Enable internet access during builds'
    )
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    projectname: str | None = Field(
        None, description='Name of the project', examples=['copr-dev']
    )
    project_dirname: str | None = Field(
        None, description='', examples=['copr-dev:pr:123']
    )
    gem_name: str | None = Field(
        None, description='Gem name from RubyGems.org', examples=['hello']
    )


class Repo(BaseModel):
    baseurl: AnyUrl | None = None
    module_hotfixes: bool | None = Field(
        None, description='Allow non-module packages to override module packages'
    )
    priority: int | None = Field(
        None,
        description='The priority value of this repository. Defaults to 99',
        examples=[42],
    )
    id: str | None = Field(None, examples=['copr_base'])
    name: str | None = Field(None, examples=['Copr repository'])


class DeleteBuilds(BaseModel):
    builds: list[int] | None = Field(None, description='List of build ids to delete')


class PackageAdd(BaseModel):
    max_builds: int | None = Field(
        None,
        description='Keep only the specified number of the newest-by-id builds (garbage collector is run daily)',
        examples=[10],
    )
    timeout: int | None = Field(
        18000,
        description='Number of seconds we allow the builds to run.',
        examples=[123123],
    )
    webhook_rebuild: bool | None = None
    packagename: str | None = Field(
        None, description='Name of the package', examples=['copr-cli']
    )
    pypi_package_name: str | None = Field(
        None, description='Package name in the Python Package Index.', examples=['copr']
    )
    pypi_package_version: str | None = Field(
        None, description='PyPI package version', examples=['1.128pre']
    )
    spec_generator: str | None = Field(
        None,
        description='Tool for generating specfile from a PyPI package. The options are full-featured pyp2rpm with cross distribution support, and pyp2spec that is being actively developed and considered to be the future.',
        examples=['pyp2spec'],
    )
    spec_template: str | None = Field(
        None,
        description='Name of the spec template. This option is limited to pyp2rpm spec generator.',
        examples=['default'],
    )
    python_versions: list[str] | None = Field(
        None,
        description='For what python versions to build. This option is limited to pyp2rpm spec generator.',
        examples=[['3', '2']],
    )
    clone_url: AnyUrl | None = Field(
        None,
        description='URL to your Git or SVN repository',
        examples=['https://github.com/fedora-copr/copr.git'],
    )
    committish: str | None = Field(
        None,
        description='Specific branch, tag, or commit that you want to build',
        examples=['main'],
    )
    spec: str | None = Field(
        None,
        description='Path to your .spec file under the specified subdirectory',
        examples=['copr-cli.spec'],
    )
    subdirectory: str | None = Field(
        None,
        description='Subdirectory where source files and .spec are located',
        examples=['cli'],
    )
    scm_type: str | None = Field("Possible values are 'git', 'svn'", examples=['git'])
    gem_name: str | None = Field(
        None, description='Gem name from RubyGems.org', examples=['hello']
    )
    script: str | None = Field(
        None,
        description='Script code to produce a SRPM package',
        examples=['#! /bin/sh -x'],
    )
    builddeps: str | None = Field(
        None,
        description='URL to additional yum repos, which can be used during build.',
        examples=['copr://@copr/copr'],
    )
    resultdir: str | None = Field(
        None,
        description='Directory where SCRIPT generates sources',
        examples=['./_build'],
    )
    chroot: str | None = Field(
        None,
        description='What chroot to run the script in',
        examples=['fedora-latest-x86_64'],
    )
    source_build_method: str | None = Field(
        None,
        description='https://docs.pagure.org/copr.copr/user_documentation.html#scm',
        examples=['tito'],
    )


class BasePackage(BaseModel):
    max_builds: int | None = Field(
        None,
        description='Keep only the specified number of the newest-by-id builds (garbage collector is run daily)',
        examples=[10],
    )
    timeout: int | None = Field(
        18000,
        description='Number of seconds we allow the builds to run.',
        examples=[123123],
    )
    webhook_rebuild: bool | None = None
    packagename: str | None = Field(
        None, description='Name of the package', examples=['copr-cli']
    )


class Project(BaseModel):
    name: str | None = Field(
        None, description='Name of the project', examples=['Copr repository']
    )
    persistent: bool | None = Field(
        None, description='Build and project is immune against deletion'
    )
    additional_repos: list[str] | None = Field(
        None, description='Additional repos to be used for builds in this chroot'
    )
    storage: str | None = Field(
        None,
        description="Admin only - what storage should be used for this project. Possible values are 'backend' or 'pulp'.",
    )
    homepage: AnyUrl | None = Field(
        None,
        description='Homepage URL of Copr project',
        examples=['https://github.com/fedora-copr'],
    )
    contact: str | None = Field(
        None, description='Contact email', examples=['pretty_user@fancydomain.uwu']
    )
    description: str | None = Field(None, description='Description of Copr project')
    instructions: str | None = Field(
        None, description='Instructions how to install and use Copr project'
    )
    devel_mode: bool | None = Field(
        None, description='If createrepo should run automatically'
    )
    unlisted_on_hp: bool | None = Field(
        None, description="Don't list Copr project on home page"
    )
    auto_prune: bool | None = Field(
        None, description='Automatically delete builds in this project'
    )
    enable_net: bool | None = Field(
        None, description='Enable internet access during builds'
    )
    bootstrap: str | None = Field(
        None,
        description="Mock bootstrap feature setup. Possible values are 'default', 'on', 'off', 'image'.",
    )
    isolation: str | None = Field(
        None,
        description="Mock isolation feature setup. Possible values are 'default', 'simple', 'nspawn'.",
        examples=['nspawn'],
    )
    module_hotfixes: bool | None = Field(
        None, description='Allow non-module packages to override module packages'
    )
    appstream: bool | None = Field(
        None, description='Enable Appstream for this project'
    )
    packit_forge_projects_allowed: str | None = Field(
        None,
        description='Whitespace separated list of forge projects that will be allowed to build in the project via Packit. Supports wildcard patterns (e.g., github.com/theproject/* will allow all repositories in the theproject organization).',
        examples=[
            'github.com/fedora-copr/copr github.com/another/project github.com/theproject/*'
        ],
    )
    follow_fedora_branching: bool | None = Field(
        None,
        description='If chroots for the new branch should be auto-enabled and populated from rawhide ones',
    )
    repo_priority: int | None = Field(
        None,
        description='The priority value of this repository. Defaults to 99',
        examples=[42],
    )
    id: int | None = Field(None, description='Numeric ID', examples=[123])
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    full_name: str | None = Field(
        None, description='Full name of the project', examples=['@copr/pull-requests']
    )
    chroot_repos: dict[str, Any] | None = None


class ProjectAdd(BaseModel):
    chroots: list[str] | None = Field(
        None,
        description='List of chroot names',
        examples=[['fedora-37-x86_64', 'fedora-rawhide-x86_64']],
    )
    bootstrap_image: str | None = Field(
        None,
        description='Name of the container image to initializethe bootstrap chroot from.  This also implies bootstrap=image.This is a noop parameter and its value is ignored.',
    )
    multilib: bool | None = None
    fedora_review: bool | None = Field(
        None, description='Run fedora-review tool for packages in this project'
    )
    runtime_dependencies: str | None = Field(
        None,
        description='List of external repositories (== dependencies, specified as baseurls) that will be automatically enabled together with this project repository.',
    )
    name: str | None = Field(
        None, description='Name of the project', examples=['Copr repository']
    )
    persistent: bool | None = Field(
        None, description='Build and project is immune against deletion'
    )
    additional_repos: list[str] | None = Field(
        None, description='Additional repos to be used for builds in this chroot'
    )
    storage: str | None = Field(
        None,
        description="Admin only - what storage should be used for this project. Possible values are 'backend' or 'pulp'.",
    )
    homepage: AnyUrl | None = Field(
        None,
        description='Homepage URL of Copr project',
        examples=['https://github.com/fedora-copr'],
    )
    contact: str | None = Field(
        None, description='Contact email', examples=['pretty_user@fancydomain.uwu']
    )
    description: str | None = Field(None, description='Description of Copr project')
    instructions: str | None = Field(
        None, description='Instructions how to install and use Copr project'
    )
    devel_mode: bool | None = Field(
        None, description='If createrepo should run automatically'
    )
    unlisted_on_hp: bool | None = Field(
        None, description="Don't list Copr project on home page"
    )
    auto_prune: bool | None = Field(
        None, description='Automatically delete builds in this project'
    )
    enable_net: bool | None = Field(
        None, description='Enable internet access during builds'
    )
    bootstrap: str | None = Field(
        None,
        description="Mock bootstrap feature setup. Possible values are 'default', 'on', 'off', 'image'.",
    )
    isolation: str | None = Field(
        None,
        description="Mock isolation feature setup. Possible values are 'default', 'simple', 'nspawn'.",
        examples=['nspawn'],
    )
    module_hotfixes: bool | None = Field(
        None, description='Allow non-module packages to override module packages'
    )
    appstream: bool | None = Field(
        None, description='Enable Appstream for this project'
    )
    packit_forge_projects_allowed: str | None = Field(
        None,
        description='Whitespace separated list of forge projects that will be allowed to build in the project via Packit. Supports wildcard patterns (e.g., github.com/theproject/* will allow all repositories in the theproject organization).',
        examples=[
            'github.com/fedora-copr/copr github.com/another/project github.com/theproject/*'
        ],
    )
    follow_fedora_branching: bool | None = Field(
        None,
        description='If chroots for the new branch should be auto-enabled and populated from rawhide ones',
    )
    repo_priority: int | None = Field(
        None,
        description='The priority value of this repository. Defaults to 99',
        examples=[42],
    )


class ProjectEdit(BaseModel):
    chroots: list[str] | None = Field(
        None,
        description='List of chroot names',
        examples=[['fedora-37-x86_64', 'fedora-rawhide-x86_64']],
    )
    bootstrap_image: str | None = Field(
        None,
        description='Name of the container image to initializethe bootstrap chroot from.  This also implies bootstrap=image.This is a noop parameter and its value is ignored.',
    )
    multilib: bool | None = None
    fedora_review: bool | None = Field(
        None, description='Run fedora-review tool for packages in this project'
    )
    runtime_dependencies: str | None = Field(
        None,
        description='List of external repositories (== dependencies, specified as baseurls) that will be automatically enabled together with this project repository.',
    )
    homepage: AnyUrl | None = Field(
        None,
        description='Homepage URL of Copr project',
        examples=['https://github.com/fedora-copr'],
    )
    contact: str | None = Field(
        None, description='Contact email', examples=['pretty_user@fancydomain.uwu']
    )
    description: str | None = Field(None, description='Description of Copr project')
    instructions: str | None = Field(
        None, description='Instructions how to install and use Copr project'
    )
    devel_mode: bool | None = Field(
        None, description='If createrepo should run automatically'
    )
    unlisted_on_hp: bool | None = Field(
        None, description="Don't list Copr project on home page"
    )
    auto_prune: bool | None = Field(
        None, description='Automatically delete builds in this project'
    )
    enable_net: bool | None = Field(
        None, description='Enable internet access during builds'
    )
    bootstrap: str | None = Field(
        None,
        description="Mock bootstrap feature setup. Possible values are 'default', 'on', 'off', 'image'.",
    )
    isolation: str | None = Field(
        None,
        description="Mock isolation feature setup. Possible values are 'default', 'simple', 'nspawn'.",
        examples=['nspawn'],
    )
    module_hotfixes: bool | None = Field(
        None, description='Allow non-module packages to override module packages'
    )
    appstream: bool | None = Field(
        None, description='Enable Appstream for this project'
    )
    packit_forge_projects_allowed: str | None = Field(
        None,
        description='Whitespace separated list of forge projects that will be allowed to build in the project via Packit. Supports wildcard patterns (e.g., github.com/theproject/* will allow all repositories in the theproject organization).',
        examples=[
            'github.com/fedora-copr/copr github.com/another/project github.com/theproject/*'
        ],
    )
    follow_fedora_branching: bool | None = Field(
        None,
        description='If chroots for the new branch should be auto-enabled and populated from rawhide ones',
    )
    repo_priority: int | None = Field(
        None,
        description='The priority value of this repository. Defaults to 99',
        examples=[42],
    )
    repos: list[str] | None = Field(
        None, description='Additional repos to be used for builds in this chroot'
    )


class ProjectFork(BaseModel):
    name: str | None = Field(
        None, description='Name of the project', examples=['Copr repository']
    )
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    confirm: bool | None = Field(
        None,
        description='If forking into a existing project, this needs to be set to True,to confirm that user is aware of that.',
    )


class ProjectDelete(BaseModel):
    verify: bool | None = None


class ProjectChroot(BaseModel):
    additional_repos: list[str] | None = Field(
        None, description='Additional repos to be used for builds in this chroot'
    )
    additional_packages: list[str] | None = Field(
        None,
        description='Additional packages to be always present in minimal buildroot',
    )
    additional_modules: list[str] | None = Field(
        None,
        description='List of modules that will be enabled or disabled in the given chroot',
        examples=[['module1:stream', '!module2:stream']],
    )
    with_opts: list[str] | None = Field(None, description='Mock --with option')
    without_opts: list[str] | None = Field(None, description='Mock --without option')
    isolation: str | None = Field(
        None,
        description="Mock isolation feature setup. Possible values are 'default', 'simple', 'nspawn'.",
        examples=['nspawn'],
    )
    mock_chroot: str | None = Field(
        None, description='Mock chroot', examples=['fedora-rawhide-x86_64']
    )
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    projectname: str | None = Field(
        None, description='Name of the project', examples=['copr-dev']
    )
    comps_name: str | None = Field(None, description='Name of the comps.xml file')
    delete_after_days: int | None = Field(
        None,
        description='The project will be automatically deleted after this many days',
        examples=[30],
    )


class ProjectChrootBuildConfig(BaseModel):
    additional_repos: list[str] | None = Field(
        None, description='Additional repos to be used for builds in this chroot'
    )
    additional_packages: list[str] | None = Field(
        None,
        description='Additional packages to be always present in minimal buildroot',
    )
    additional_modules: list[str] | None = Field(
        None,
        description='List of modules that will be enabled or disabled in the given chroot',
        examples=[['module1:stream', '!module2:stream']],
    )
    with_opts: list[str] | None = Field(None, description='Mock --with option')
    without_opts: list[str] | None = Field(None, description='Mock --without option')
    isolation: str | None = Field(
        None,
        description="Mock isolation feature setup. Possible values are 'default', 'simple', 'nspawn'.",
        examples=['nspawn'],
    )
    chroot: str | None = Field(
        None,
        description='What chroot to run the script in',
        examples=['fedora-latest-x86_64'],
    )
    enable_net: bool | None = Field(
        None, description='Enable internet access during builds'
    )
    repos: list[Repo] | None = None


class BuildChroot(BaseModel):
    started_on: int | None = Field(
        None, description='Timestamp when the build started', examples=[1677695545]
    )
    ended_on: int | None = Field(
        None, description='Timestamp when the build ended', examples=[1677695963]
    )
    state: str | None = Field(None, description='', examples=['succeeded'])
    name: str | None = Field(
        None, description='Mock chroot', examples=['fedora-rawhide-x86_64']
    )
    result_url: AnyUrl | None = None


class BuildChrootConfig(BaseModel):
    additional_repos: list[str] | None = Field(
        None, description='Additional repos to be used for builds in this chroot'
    )
    additional_packages: list[str] | None = Field(
        None,
        description='Additional packages to be always present in minimal buildroot',
    )
    with_opts: list[str] | None = Field(None, description='Mock --with option')
    without_opts: list[str] | None = Field(None, description='Mock --without option')
    enable_net: bool | None = Field(
        None, description='Enable internet access during builds'
    )
    is_background: bool | None = Field(
        None, description='The build is marked as a background job'
    )
    memory_limit: int | None = None
    timeout: int | None = Field(
        18000,
        description='Number of seconds we allow the builds to run.',
        examples=[123123],
    )
    bootstrap: str | None = Field(
        None,
        description="Mock bootstrap feature setup. Possible values are 'default', 'on', 'off', 'image'.",
    )
    bootstrap_image: str | None = Field(
        None,
        description='Name of the container image to initializethe bootstrap chroot from.  This also implies bootstrap=image.This is a noop parameter and its value is ignored.',
    )
    repos: list[Repo] | None = None


class Nevra(BaseModel):
    arch: str | None = Field(None, examples=['x86_64'])
    epoch: int | None = Field(None, examples=[3])
    release: str | None = Field(None, examples=['1.fc39'])
    version: str | None = Field(None, examples=['1.0'])
    name: str | None = Field(None, description='Package name')


class CanBuildSchema(BaseModel):
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    projectname: str | None = Field(
        None, description='Name of the project', examples=['copr-dev']
    )
    who: str | None = Field(None, examples=['user123'])
    can_build_in: bool | None = Field(None, examples=[True])


class WebhookSecret(BaseModel):
    id: int | None = Field(None, description='Numeric ID', examples=[123])
    name: str | None = Field(
        None, description='Name of the project', examples=['Copr repository']
    )
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    full_name: str | None = Field(
        None, description='Full name of the project', examples=['@copr/pull-requests']
    )
    webhook_secret: str | None = Field(
        None, examples=['really-secret-string-do-not-share']
    )


class FieldModulePackage(BaseModel):
    name: str | None = Field(
        None, description='Name of the project', examples=['Copr repository']
    )
    chroots: dict[str, Any] | None = Field(
        None,
        description='Chroots and their states',
        examples=[
            {'fedora-rawhide-i386': {'state': 'waiting', 'status': 1, 'build_id': 1}}
        ],
    )


class SourceDictScm(BaseModel):
    clone_url: AnyUrl | None = Field(
        None,
        description='URL to your Git or SVN repository',
        examples=['https://github.com/fedora-copr/copr.git'],
    )
    committish: str | None = Field(
        None,
        description='Specific branch, tag, or commit that you want to build',
        examples=['main'],
    )
    spec: str | None = Field(
        None,
        description='Path to your .spec file under the specified subdirectory',
        examples=['copr-cli.spec'],
    )
    subdirectory: str | None = Field(
        None,
        description='Subdirectory where source files and .spec are located',
        examples=['cli'],
    )
    source_build_method: str | None = Field(
        None,
        description='https://docs.pagure.org/copr.copr/user_documentation.html#scm',
        examples=['tito'],
    )
    type: str | None = Field("Possible values are 'git', 'svn'", examples=['git'])


class SourceDictPyPI(BaseModel):
    pypi_package_name: str | None = Field(
        None, description='Package name in the Python Package Index.', examples=['copr']
    )
    pypi_package_version: str | None = Field(
        None, description='PyPI package version', examples=['1.128pre']
    )
    spec_generator: str | None = Field(
        None,
        description='Tool for generating specfile from a PyPI package. The options are full-featured pyp2rpm with cross distribution support, and pyp2spec that is being actively developed and considered to be the future.',
        examples=['pyp2spec'],
    )
    spec_template: str | None = Field(
        None,
        description='Name of the spec template. This option is limited to pyp2rpm spec generator.',
        examples=['default'],
    )
    python_versions: list[str] | None = Field(
        None,
        description='For what python versions to build. This option is limited to pyp2rpm spec generator.',
        examples=[['3', '2']],
    )


class ModuleBuild(BaseModel):
    nsv: str | None = Field(
        None,
        description='NSV of the module build in format name-stream-version.',
        examples=['name-stream-version'],
    )


class ModuleAdd(BaseModel):
    modulemd: dict[str, Any] | None = Field(
        None, description='Modulemd YAML file', examples=['YAML file']
    )
    distgit: str | None = Field(
        None, description='Dist-git URL we build against', examples=['fedora']
    )
    scmurl: AnyUrl | None = None


class Build(BaseModel):
    chroots: list[str] | None = Field(
        None,
        description='List of chroot names',
        examples=[['fedora-37-x86_64', 'fedora-rawhide-x86_64']],
    )
    ended_on: int | None = Field(
        None, description='Timestamp when the build ended', examples=[1677695963]
    )
    id: int | None = Field(None, description='Numeric ID', examples=[123])
    is_background: bool | None = Field(
        None, description='The build is marked as a background job'
    )
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    project_dirname: str | None = Field(
        None, description='', examples=['copr-dev:pr:123']
    )
    projectname: str | None = Field(
        None, description='Name of the project', examples=['copr-dev']
    )
    repo_url: AnyUrl | None = Field(
        None,
        description='See REPO OPTIONS in `man 5 dnf.conf`',
        examples=[
            'https://download.copr.fedorainfracloud.org/results/@copr/copr-dev/fedora-$releasever-$basearch/'
        ],
    )
    started_on: int | None = Field(
        None, description='Timestamp when the build started', examples=[1677695545]
    )
    state: str | None = Field(None, description='', examples=['succeeded'])
    submitted_on: int | None = Field(
        None,
        description='Timestamp when the build was submitted',
        examples=[1677695304],
    )
    submitter: str | None = Field(
        None,
        description='Username of the person who submitted this build',
        examples=['frostyx'],
    )
    source_package: SourcePackage | None = None


class Pagination(BaseModel):
    items: list[Build] | None = None
    meta: PaginationMeta | None = None


class CreateBuildCustom(BaseModel):
    chroot_names: list[str] | None = Field(
        None,
        description='List of chroot names',
        examples=[['fedora-37-x86_64', 'fedora-rawhide-x86_64']],
    )
    background: bool | None = Field(
        None, description='The build is marked as a background job'
    )
    timeout: int | None = Field(
        18000,
        description='Number of seconds we allow the builds to run.',
        examples=[123123],
    )
    bootstrap: str | None = Field(
        None,
        description="Mock bootstrap feature setup. Possible values are 'default', 'on', 'off', 'image'.",
    )
    isolation: str | None = Field(
        None,
        description="Mock isolation feature setup. Possible values are 'default', 'simple', 'nspawn'.",
        examples=['nspawn'],
    )
    after_build_id: int | None = Field(
        None,
        description='Build after the batch containing the Build ID build',
        examples=[123],
    )
    with_build_id: int | None = Field(
        None,
        description='Build in the same batch with the Build ID build',
        examples=[123],
    )
    enable_net: bool | None = Field(
        None, description='Enable internet access during builds'
    )
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    projectname: str | None = Field(
        None, description='Name of the project', examples=['copr-dev']
    )
    script: str | None = Field(
        None,
        description='Script code to produce a SRPM package',
        examples=['#! /bin/sh -x'],
    )
    chroot: str | None = Field(
        None,
        description='What chroot to run the script in',
        examples=['fedora-latest-x86_64'],
    )
    builddeps: str | None = Field(
        None,
        description='URL to additional yum repos, which can be used during build.',
        examples=['copr://@copr/copr'],
    )
    resultdir: str | None = Field(
        None,
        description='Directory where SCRIPT generates sources',
        examples=['./_build'],
    )
    project_dirname: str | None = Field(
        None, description='', examples=['copr-dev:pr:123']
    )
    repos: list[Repo] | None = None


class PackageBuilds(BaseModel):
    latest: Build | None = None
    latest_succeeded: Build | None = None


class NevraPackages(BaseModel):
    packages: list[Nevra] | None = None


class Monitor(BaseModel):
    message: str | None = Field(None, examples=['Project monitor request successful'])
    output: str | None = Field(None, examples=['ok'])
    packages: list[FieldModulePackage] | None = None


class Package(BaseModel):
    id: int | None = Field(None, description='Numeric ID', examples=[123])
    name: str | None = Field(
        None, description='Name of the package', examples=['copr-cli']
    )
    ownername: str | None = Field(
        None, description='User or group name', examples=['@copr']
    )
    projectname: str | None = Field(
        None, description='Name of the project', examples=['copr-dev']
    )
    source_type: str | None = Field(
        None,
        description='See https://python-copr.readthedocs.io/en/latest/client_v3/package_source_types.html',
        examples=['scm'],
    )
    source_dict: dict[str, Any] | None = Field(
        None,
        description='http://python-copr.readthedocs.io/en/latest/client_v3/package_source_types.html',
    )
    auto_rebuild: bool | None = Field(
        None, description='Auto-rebuild the package? (i.e. every commit or new tag)'
    )
    builds: PackageBuilds | None = None
